# Generated by Django 5.1.2 on 2024-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип публикуемого объявление'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
    ]
